[package]
name = "{{name}}"
version = "0.1.0"
authors = ["[your_name] <[your_email]>"]
edition = "2018"

[dependencies]
ink_metadata = { git = "https://github.com/paritytech/ink", branch = "aj-extra-metadata", package = "ink_metadata", default-features = false, features = ["derive"], optional = true }
ink_primitives = { git = "https://github.com/paritytech/ink", branch = "aj-extra-metadata", default-features = false }
ink_core = { git = "https://github.com/paritytech/ink", branch = "aj-extra-metadata", package = "ink_core", default-features = false }
ink_lang = { git = "https://github.com/paritytech/ink", branch = "j", package = "ink_lang", default-features = false }

scale = { package = "parity-scale-codec", version = "1.3", default-features = false, features = ["derive"] }
scale-info = { version = "0.3", default-features = false, features = ["derive"], optional = true }

[lib]
name = "{{name}}"
path = "lib.rs"
crate-type = [
	# Used for normal contract Wasm blobs.
	"cdylib",
]

[features]
default = ["std"]
std = [
    "ink_metadata/std",
    "ink_core/std",
    "ink_primitives/std",
    "scale/std",
    "scale-info/std",
]
ink-as-dependency = []
