[package]
name = "{{name}}"
version = "0.1.0"
authors = ["[your_name] <[your_email]>"]scale
edition = "2018"
resolver = "2"

[dependencies]
ink_primitives = { version = "3.0.0-rc5", default-features = false }
ink_metadata = { version = "3.0.0-rc5", default-features = false, features = ["derive"], optional = true }
ink_env = { version = "3.0.0-rc5", default-features = false }
ink_storage = { version = "3.0.0-rc5", default-features = false }
ink_lang = { version = "3.0.0-rc5", default-features = false }

scale = { package = "parity-scale-codec", version = "2.1", default-features = false, features = ["derive"] }
scale-info = { version = "1.0", default-features = false, features = ["derive"], optional = true }

[lib]
name = "{{name}}"
path = "lib.rs"
crate-type = [
	# Used for normal contract Wasm blobs.
	"cdylib",
]

[features]
default = ["std"]
std = [
    "ink_metadata/std",
    "ink_env/std",
    "ink_storage/std",
    "ink_primitives/std",
    "scale/std",
    "scale-info/std",
]
ink-as-dependency = []

[patch.crates-io]
ink_primitives = { git = "https://github.com/paritytech/ink/", branch = "master", package = "ink_primitives" }
ink_metadata = { git = "https://github.com/paritytech/ink/", branch = "master", package = "ink_metadata" }
ink_env = { git = "https://github.com/paritytech/ink/", branch = "master", package = "ink_env" }
ink_storage = { git = "https://github.com/paritytech/ink/", branch = "master", package = "ink_storage" }
ink_lang = { git = "https://github.com/paritytech/ink/", branch = "master", package = "ink_lang" }
